config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :diagnostics, only: %i[index new create destroy]
  resources :animals
  resources :farms
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'main#index'
end

app/models/animal.rb
# frozen_string_literal: true

class Animal < ApplicationRecord
  belongs_to :farm
  has_many :diagnostics, dependent: :delete_all
  has_one_attached :picture do |attachable|
    attachable.variant :thumb, resize_to_limit: [200, 200], preprocess: false
  end

  validates :gender, :race, presence: true

  scope :belonging_to_user, lambda { |user_id|
    joins(farm: :user).where(farms: { user_id: }).order(created_at: :desc)
  }

  scope :count_for_user, lambda { |user_id|
    joins(farm: :user).where(users: { id: user_id }).count
  }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/diagnostic.rb
# frozen_string_literal: true

class Diagnostic < ApplicationRecord
  belongs_to :animal

  scope :belonging_to_user, lambda { |user_id|
    joins(animal: { farm: :user }).where(farms: { user_id: }).order(created_at: :desc)
  }

  scope :count_for_user, lambda { |user_id|
    joins(animal: { farm: :user }).where(farms: { user_id: }).count
  }
end

app/models/farm.rb
# frozen_string_literal: true

class Farm < ApplicationRecord
  belongs_to :user
  has_many :animals, inverse_of: :farm, dependent: :delete_all

  validates :name, :address, :area, :user, presence: true

  scope :count_for_user, ->(user_id) { where(user_id:).count }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :farms, inverse_of: :user

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  normalizes :email, with: ->(email) { email.strip.downcase }
end

app/controllers/animals_controller.rb
# frozen_string_literal: true

class AnimalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_animal, only: %i[show edit update destroy]
  before_action :set_farms, only: %i[new edit]

  def index
    @animals = Animal.belonging_to_user(current_user.id)
  end

  def show
    @diagnostics = Diagnostic.where(animal_id: @animal.id)
  end

  def new
    @animal = Animal.new
    @races = json_collection :races
  end

  def edit; end

  def create
    @animal = Animal.new(animal_params)
    @animal.encoded_race = json_collection(:races).select { |r| r.name == animal_params[:race] }.first.id
    puts @animal.inspect

    if @animal.save
      redirect_to animal_url(@animal), notice: 'Animal was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @animal.update(animal_params)
      redirect_to animal_url(@animal), notice: 'Animal was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @animal.destroy!

    redirect_to animals_url, notice: 'Animal was successfully destroyed.'
  end

  private

  def set_animal
    @animal = Animal.find(params[:id])
  end

  def set_farms
    @farms = Farm.where(user_id: current_user.id)
  end

  def animal_params
    params.require(:animal).permit(:name, :race, :gender, :picture, :weight, :birth_at, :farm_id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Shared
end

app/controllers/concerns/shared.rb
# frozen_string_literal: true

require 'json'

module Shared
  def json_collection(name)
    path = Rails.root.join('data', "#{name}.json")
    JSON.parse(File.read(path), object_class: OpenStruct)
  end
end

app/controllers/diagnostics_controller.rb
# frozen_string_literal: true

require 'httparty'

class DiagnosticsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_diagnostic, only: [:destroy]

  def index
    @diagnostics = Diagnostic.belonging_to_user(current_user.id)
  end

  def new
    @diagnostic = Diagnostic.new
    @animals = Animal.belonging_to_user(current_user.id)
    @symptoms = json_collection :symptoms
  end

  def create
    @diagnostic = Diagnostic.new(diagnostic_params)
    @diagnostic.symptoms = diagnostic_params[:symptoms].reject(&:empty?).join(', ')

    if @diagnostic.save
      predictions = fetch_predictions(@diagnostic)
      @diagnostic.update(predictions:)

      redirect_to diagnostics_url, notice: 'Diagnostic was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @diagnostic.destroy!

    redirect_to diagnostics_url, notice: 'Diagnostic was successfully destroyed.'
  end

  private

  def fetch_predictions(diagnostic)
    symptoms = prepare_symptoms(diagnostic)
    request = { features: symptoms }
    response = HTTParty.post(
      'https://ml.ecovet.cloud/predict',
      body: JSON.generate(request),
      headers: { 'Content-Type' => 'application/json' }
    )

    predictions = JSON.parse(response.body)['predictions']
    "#{predictions['lgbm']}, #{predictions['xgb']}"
  end

  def prepare_symptoms(diagnostic)
    symptoms = diagnostic.symptoms.split(',').map(&:strip).map(&:to_i)
    symptoms.prepend diagnostic.animal.encoded_race
    symptoms.fill(118, symptoms.size, 7 - symptoms.size) if symptoms.size < 7
    symptoms
  end

  def set_diagnostic
    @diagnostic = Diagnostic.find(params[:id])
  end

  def diagnostic_params
    params.require(:diagnostic).permit(:animal_id, symptoms: [])
  end
end

app/controllers/farms_controller.rb
# frozen_string_literal: true

class FarmsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_farm, only: %i[show edit update destroy]

  def index
    @farms = Farm.where(user_id: current_user.id)
  end

  def show; end

  def new
    @farm = Farm.new
  end

  def edit; end

  def create
    @farm = Farm.new(farm_params)
    @farm.user = current_user

    if @farm.save
      redirect_to farms_url, notice: 'Farm was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @farm.update(farm_params)
      redirect_to farm_url(@farm), notice: 'Farm was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @farm.destroy!

    redirect_to farms_url, notice: 'Farm was successfully destroyed.'
  end

  private

  def set_farm
    @farm = Farm.find(params[:id])

    return if @farm.user_id.equal? current_user.id

    redirect_to farms_url, alert: "You don't have permission to view this farm"
  end

  def farm_params
    params.require(:farm).permit(:name, :address, :area)
  end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  before_action :authenticate_user!

  def index
    @farms_count = Farm.count_for_user(current_user.id)
    @animals_count = Animal.count_for_user(current_user.id)
    @diagnostics_count = Diagnostic.count_for_user(current_user.id)
    @diagnostics = Diagnostic.belonging_to_user(current_user.id).limit(5)
  end
end

app/helpers/animals_helper.rb
# frozen_string_literal: true

module AnimalsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def encoding_names(type, ids)
    path = Rails.root.join('data', "#{type}.json")
    data = JSON.parse(File.read(path), object_class: OpenStruct)

    ids = ids.split(',').map(&:strip).map(&:to_i)
    id_to_name = data.each_with_object({}) do |item, hash|
      hash[item[:id]] = item[:name]
    end

    ids.map { |id| id_to_name[id] || id }
  end
end

app/helpers/diagnostics_helper.rb
# frozen_string_literal: true

module DiagnosticsHelper
end

app/helpers/farms_helper.rb
# frozen_string_literal: true

module FarmsHelper
end

app/helpers/tags_helper.rb
# frozen_string_literal: true

module TagsHelper
  def icon_tag(name)
    "<em class='icon ni ni-#{name}' aria-label='#{name}'></em>".html_safe
  end

  def header_link_tag(link, label, icon)
    "<li class='nk-block-tools-opt'>
      <a href='#{link}' class='btn btn-white btn-dim btn-outline-light'>
        #{icon_tag(icon)}
        <span>#{label}</span>
      </a>
    </li>".html_safe
  end
end

app/views/animals/_animal.html.erb
<div id="<%= dom_id animal %>">
  <div class="card">
    <div class="card-content">
      <div class="card-inner">
        <div class="nk-block">
          <div class="nk-block-head">
            <h5 class="title">Information</h5>
          </div>
          <div class="profile-ud-list">
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Photo</span>
                <span class="profile-ud-value">
                  <%= image_tag animal.picture.attached? ? animal.picture.variant(:thumb) : '/images/default.png', width: 80, height: 80 %>
                </span>
              </div>
            </div>
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Nom</span>
                <span class="profile-ud-value"><%= animal.name %></span>
              </div>
            </div>
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Ferme</span>
                <span class="profile-ud-value"><%= link_to animal.farm.name, animal.farm %></span>
              </div>
            </div>
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Race</span>
                <span class="profile-ud-value"><%= animal.race %></span>
              </div>
            </div>
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Encoded Race</span>
                <span class="profile-ud-value"><%= animal.encoded_race %></span>
              </div>
            </div>
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Genre</span>
                <span class="profile-ud-value"><%= animal.gender %></span>
              </div>
            </div>
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Poids</span>
                <span class="profile-ud-value"><%= animal.weight %> kg</span>
              </div>
            </div>
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Date de création</span>
                <span class="profile-ud-value"><%= animal.created_at %></span>
              </div>
            </div>
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Date d'actualisation</span>
                <span class="profile-ud-value"><%= animal.updated_at %></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/animals/_form.html.erb
<div class="card">
  <div class="card-inner">
    <%= bootstrap_form_for(animal, url: animal.id.nil? ? animals_path : animal_path(animal)) do |f| %>
      <% animal.errors.each do |error| %>
        <div data-controller="flash" data-type="error" data-message="<%= error.full_message %>" data-timer="5000"></div>
      <% end %>

      <div class="row">
        <div class="col-12 col-md-6"><%= f.text_field :name, label: 'Nom', class: 'form-control-lg' %></div>
        <div class="col-12 col-md-6"><%= f.text_field :race, label: 'Race', class: 'form-control-lg' %></div>
        <div class="col-12 col-md-6"><%= f.select :gender, [%w[M M], %w[F F]], label: 'Genre', class: 'form-control-lg' %></div>
        <div class="col-12 col-md-6"><%= f.file_field :picture, label: 'Photo', class: 'form-control-lg', 'data-controller': 'image' %></div>
      </div>

      <%= f.number_field :weight, label: 'Poids', append: ['Kilogrammes'], class: 'form-control-lg' %>
      <%= f.date_field :birth_at, label: 'Date de naissance', class: 'form-control-lg' %>
      <%= f.collection_select :farm_id, @farms, :id, :name, label: 'Ferme', class: 'form-control-lg' %>

      <%= f.submit "Créer", class: 'mt-3 btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/animals/edit.html.erb
<%= content_for :title, 'Éditer un animal' %>

<%= render :layout => 'components/header', locals: {title: 'Éditer un animal'} do %>
  <%= header_link_tag animal_path(@animal), 'Détails', 'eye'  %>
<% end %>

<%= render "form", animal: @animal %>

app/views/animals/index.html.erb
<%= content_for :title, 'Tous les animaux' %>

<%= render :layout => 'components/header', locals: {title: 'Tous les animaux'} do %>
  <%= header_link_tag new_animal_path, 'Nouveau', 'plus' %>
<% end %>

<% if @animals.blank? %>
  <%= render :partial => 'components/empty_state' %>
<% else %>
  <div class="card card-preview">
    <table class="table table-tranx">
      <thead>
      <tr class="tb-tnx-head">
        <th>#</th>
        <th>Image</th>
        <th>Nom</th>
        <th>Race</th>
        <th>Poids</th>
        <th>Naissance</th>
        <th>Ferme</th>
        <th class="tb-tnx-action">
          <span>&nbsp;</span>
        </th>
      </tr>
      </thead>
      <tbody>
      <% @animals.each do |animal| %>
        <tr class="tb-tnx-item">
          <td><%= link_to animal.id, animal %></td>
          <td><%= image_tag animal.picture.attached? ? animal.picture.variant(:thumb) : '/images/default.png', width: 80, height: 80 %></td>
          <td><%= animal.name %></td>
          <td><%= animal.race %></td>
          <td><%= animal.weight %></td>
          <td><%= animal.birth_at %></td>
          <td><%= link_to animal.farm.name, animal.farm %></td>
          <td class="tb-tnx-action">
            <%= link_to icon_tag("eye"), animal, class: 'text-soft btn btn-icon btn-trigger' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/animals/new.html.erb
<%= content_for :title, 'Ajouter un animal' %>

<%= render :partial => 'components/header', locals: {title: 'Ajouter un animal'} %>
<%= render "form", animal: @animal %>

app/views/animals/show.html.erb
<%= content_for :title, "Animal #{@animal.name}" %>

<%= render :layout => 'components/header', locals: {title: "Animal ##{@animal.id}"} do %>
  <%= header_link_tag new_diagnostic_path, 'Diagnostiquer', 'notify'  %>
  <%= header_link_tag edit_animal_path(@animal), 'Modifier', 'edit'  %>
  <li class='nk-block-tools-opt'>
    <%= link_to animal_path(@animal), class: 'btn btn-danger', data: {turbo_method: :delete, turbo_confirm: 'êtes vous sûre ?'} do %>
      <%= icon_tag 'trash' %>
      <span>Supprimer</span>
    <% end %>
  </li>
<% end %>

<%= render @animal %>

<div class="nk-block-head mt-4">
  <h5 class="title">Diagnostiques récents</h5>
</div>
<div class="card ">
  <div class="card-content">
    <% if @diagnostics.empty? %>
      <%= render :partial => 'components/empty_state' %>
    <% else %>
      <%= render partial: 'diagnostics/diagnostics', locals: {diagnostics: @diagnostics} %>
    <% end %>
  </div>
</div>

app/views/diagnostics/_diagnostic.html.erb
<div id="<%= dom_id diagnostic %>">
</div>

app/views/diagnostics/_diagnostics.html.erb
<table class="table table-tranx">
  <thead>
  <tr class="tb-tnx-head">
    <th>Animal</th>
    <th>Race</th>
    <th>Symptômes</th>
    <th>Prédictions</th>
    <th class="tb-tnx-action">
      <span>&nbsp;</span>
    </th>
  </tr>
  </thead>
  <tbody>
  <% diagnostics.each do |diagnostic| %>
    <tr class="tb-tnx-item">
      <td><%= link_to "Animal ##{diagnostic.animal.id}", diagnostic.animal %></td>
      <td><span class="badge badge-dim badge-sm bg-primary"><%= diagnostic.animal.race %></span></td>
      <td>
        <ul>
          <% encoding_names('symptoms', diagnostic.symptoms).each do |symptom| %>
            <li><%= symptom %></li>
          <% end %>
        </ul>
      </td>
      <td>
        <% unless diagnostic.predictions.nil? %>
          <ul>
            <% diagnostic.predictions.split(', ').each do |prediction| %>
              <li><%= prediction %></li>
            <% end %>
          </ul>
        <% end %>
      </td>
      <td class="tb-tnx-action">
        <%= link_to diagnostic, class: 'text-soft btn btn-icon btn-trigger', data: {turbo_method: :delete, turbo_confirm: 'êtes vous sûre ?'} do %>
          <%= icon_tag 'trash' %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/diagnostics/_form.html.erb
<div class="card">
  <div data-controller="select" class="card-inner">
    <%= bootstrap_form_with(model: diagnostic, url: diagnostics_path) do |f| %>
      <% if diagnostic.errors.any? %>
        <div data-controller="flash" data-type="error" data-message="<%= error.full_message %>" data-timer="5000"></div>
      <% end %>

      <%= f.collection_select :animal_id, @animals, :id, :name, label: 'Animal', class: 'form-control-lg' %>
      <%= f.collection_select :symptoms, @symptoms, :id, :name, multiple: true, label: 'Symptômes', class: 'form-control-lg' %>

      <%= f.submit "Soumettre", class: 'mt-3 btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/diagnostics/index.html.erb
<%= content_for :title, 'Tous les diagnostics' %>

<%= render layout: 'components/header', locals: {title: 'Tous les diagnostics'} do %>
  <%= header_link_tag new_diagnostic_path, 'Nouveau', 'plus' %>
<% end %>

<% if @diagnostics.blank? %>
  <%= render partial: 'components/empty_state' %>
<% else %>
  <div class="card card-preview">
    <%= render partial: 'diagnostics/diagnostics', locals: {diagnostics: @diagnostics} %>
  </div>
<% end %>

app/views/diagnostics/new.html.erb
<%= content_for :title, "Obtenir un diagnostique" %>

<%= render :partial => 'components/header', locals: {title: "Obtenir un diagnostique"} %>

<%= render "form", diagnostic: @diagnostic %>

app/views/farms/_farm.html.erb
<div class="card">
  <div class="card-aside-wrap">
    <div class="card-content">
      <div class="card-inner">
        <div class="nk-block">
          <div class="nk-block-head">
            <h5 class="title">Information</h5>
          </div>

          <div class="profile-ud-list">
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Propriétaire</span>
                <span class="profile-ud-value"><%= farm.user.email %></span>
              </div>
            </div>
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Nom</span>
                <span class="profile-ud-value"><%= farm.name %></span>
              </div>
            </div>
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Adresse</span>
                <span class="profile-ud-value"><%= farm.address %>
                </span>
              </div>
            </div>
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Superficie</span>
                <span class="profile-ud-value"><%= farm.area %> KM<sup>2</sup></span>
              </div>
            </div>
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Date de création</span>
                <span class="profile-ud-value"><%= farm.created_at %></span>
              </div>
            </div>
            <div class="profile-ud-item">
              <div class="profile-ud wider">
                <span class="profile-ud-label">Date d'actualisation</span>
                <span class="profile-ud-value"><%= farm.updated_at %></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/farms/_form.html.erb
<div class="card">
  <div class="card-inner">
    <%= bootstrap_form_for(farm, url: farm.id.nil? ? farms_path : farm_path(farm) ) do |f| %>
      <% farm.errors.each do |error| %>
        <div data-controller="flash" data-type="error" data-message="<%= error.full_message %>" data-timer="5000"></div>
      <% end %>

      <%= f.text_field :name, label: 'Nom', class: 'form-control-lg' %>
      <%= f.text_field :address, label: 'Address', class: 'form-control-lg' %>
      <%= f.number_field :area, label: 'Superficie', class: 'form-control-lg' %>

      <%= f.submit "Créer", class: 'mt-3 btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/farms/edit.html.erb
<%= content_for :title, 'Éditer une ferme' %>

<%= render :layout => 'components/header', locals: {title: 'Éditer une ferme'} do %>
  <%= header_link_tag farm_path(@farm), 'Détails', 'eye'  %>
<% end %>

<%= render "form", farm: @farm %>

app/views/farms/index.html.erb
<%= content_for :title, 'Toutes les fermes' %>

<%= render :layout => 'components/header', locals: {title: 'Toutes les fermes'} do %>
  <%= header_link_tag new_farm_path, 'Nouveau', 'plus'  %>
<% end %>

<% if @farms.blank? %>
  <%= render :partial => 'components/empty_state' %>
<% else %>
  <div class="card card-preview">
    <table class="table table-tranx">
      <thead>
      <tr class="tb-tnx-head">
        <th>#</th>
        <th>Nom</th>
        <th>Adresse</th>
        <th>Superficie</th>
        <th class="tb-tnx-action">
          <span>&nbsp;</span>
        </th>
      </tr>
      </thead>
      <tbody>
        <% @farms.each do |farm| %>
          <tr class="tb-tnx-item">
            <td><%= link_to farm.id, farm %></td>
            <td><%= farm.name %></td>
            <td><%= farm.address %></td>
            <td><%= farm.area %> KM<sup>2</sup></td>
            <td class="tb-tnx-action">
              <%= link_to icon_tag("eye"), farm, class: 'text-soft btn btn-icon btn-trigger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/farms/new.html.erb
<%= content_for :title, 'Créer une ferme' %>

<%= render :partial => 'components/header', locals: {title: 'Créer une ferme'} %>

<%= render "form", farm: @farm %>

app/views/farms/show.html.erb
<%= content_for :title, "Ferme #{@farm.name}" %>

<%= render :layout => 'components/header', locals: {title: "Ferme #{@farm.name}"} do %>
  <%= header_link_tag edit_farm_path(@farm), 'Modifier', 'edit'  %>
  <li class='nk-block-tools-opt'>
    <%= link_to farm_path(@farm), class: 'btn btn-danger', data: {turbo_method: :delete, turbo_confirm: 'êtes vous sûre ?'} do %>
      <%= icon_tag 'trash' %>
      <span>Supprimer</span>
    <% end %>
  </li>
<% end %>

<%= render @farm %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">
  <meta name="author" content="ecovet">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= favicon_link_tag 'icon_light.png' %>

  <title><%= yield :title %> | Ecovet</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: "defer" %>
  <%= javascript_include_tag "/javascripts/bundle.js", "data-turbo-track": 'reload', defer: "defer" %>
  <%= javascript_include_tag "/javascripts/scripts.js", "data-turbo-track": 'reload', defer: "defer" %>
  <%= tag :meta, name: :detection_model_url, content: ENV.fetch('DETECTION_MODEL_URL', 'http://localhost:5000/detect') %>
  <%= yield :meta_tags %>
</head>
<body class="nk-body bg-theme has-sidebar ui-shady">
<%= render 'components/flash' %>
<div class="nk-app-root">
  <div class="nk-main">
    <% if content_for? :sidebar %>
      <%= yield :sidebar %>
    <% else %>
      <%= render 'components/sidebar' %>
    <% end %>
    <div class="nk-wrap">
      <% if content_for? :navbar %>
        <%= yield :navbar %>
      <% else %>
        <%= render 'components/navbar' %>
      <% end %>
      <div class="nk-content">
        <div class="container-fluid">
          <div class="nk-content-inner">
              <div class="nk-content-body">
                <div class="wide-md mx-auto">
                  <% if content_for? :header %>
                    <%= yield :header %>
                  <% end %>
                  <div class="nk-block">
                    <%= yield %>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>
      <% if content_for? :footer %>
        <%= yield :footer %>
      <% else %>
        <%= render 'components/footer' %>
      <% end %>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>" class="js">
<head>
  <meta charset="utf-8">
  <meta name="author" content="Ecovet">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" href="">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <title><%= yield :title %> | Ecovet </title>
</head>

<body class="nk-body bg-white npc-default pg-auth">
<%= render 'components/flash' %>
<div class="nk-app-root">
  <div class="nk-main ">
    <div class="nk-wrap nk-wrap-nosidebar">
      <div class="nk-content ">
        <div class="nk-split nk-split-page nk-split-md">
          <div class="nk-split-content nk-block-area nk-block-area-column nk-auth-container bg-white shadow-sm z-3">
            <div class="nk-block nk-block-middle nk-auth-body">
              <div class="brand-logo pb-5">
                <%= link_to root_path, class: 'logo-link' do %>
                  <%= image_tag 'logo_dark.png', class: 'logo-img logo-img-lg', alt: 'logo ecovet' %>
                <% end %>
              </div>
              <%= yield %>
            </div>
            <% if content_for? :footer %>
              <%= yield :footer %>
            <% else %>
              <div class="nk-block nk-auth-footer">
                <div class="mt-3"><p>© <%= Time.now.strftime("%Y") %> Tout droits réservés Ecovet Systems.</p></div>
              </div>
            <% end %>
          </div>
          <div
            id="bg"
            class="nk-split-content nk-split-stretch bg-abstract z-1"
            style="background-image: url('https://images.pexels.com/photos/933648/pexels-photo-933648.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'); background-size: cover"
          ></div>
      </div>
    </div>
  </div>
</div>
</div>
</body>
</html>